name: Rust Build

env:
  PLUGIN_NAME: 'libparam_hook.nro'
  VERSION: 'v13.0.4'


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  plugin:
    name: Plugin NRO
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          target: x86_64-unknown-linux-gnu
      - uses: Swatinem/rust-cache@v2
        name: Rust Cache
        with:
          prefix-key: "plugin"
          cache-all-crates: true
      - name: Install Skyline
        run: |
          cargo install --git https://github.com/Raytwo/cargo-skyline --branch std-change --force
          cargo-skyline skyline update-std
      - name: Build NRO
        run: cargo skyline build --release

      - name: Upload plugin artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin
          path: target/aarch64-skyline-switch/release/${{env.PLUGIN_NAME}}
  upload:
    runs-on: ubuntu-latest
    needs:
      - plugin
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
    - name: Display structure of downloaded files
      run: ls -R
    - name: Upload release
      uses: meeDamian/github-release@2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: false
        allow_override: true
        gzip: false
        tag: ${{env.VERSION}}
        name: ${{env.VERSION}}
        body: Build of ${{env.PLUGIN_NAME}} from master.
        files: ./plugin/${{env.PLUGIN_NAME}}
