name: Rust Build

env:
  PLUGIN_NAME: 'libparam_hook.nro'
  VERSION: 'v13.0.1'

on:
  push:
    branches: [ master ]
jobs:
  plugin:
    name: Plugin NRO
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          target: x86_64-unknown-linux-gnu
      - name: Install Skyline
        run: |
          cargo install cargo-skyline
          cargo-skyline skyline update-std
      - name: Build release NRO
        id: build_release
        run: RUSTFLAGS=-g cargo-skyline skyline build --release
      - name: Upload plugin artifact
        uses: actions/upload-artifact@v3
        with:
          name: plugin
          path: target/aarch64-skyline-switch/release/${{env.PLUGIN_NAME}}
  upload:
    runs-on: ubuntu-latest
    needs:
      - plugin
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v2
    - name: Display structure of downloaded files
      run: ls -R
    - name: Upload release
      uses: meeDamian/github-release@2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: true
        allow_override: true
        gzip: false
        tag: ${{env.VERSION}}
        name: ${{env.VERSION}}
        body: Build of ${{env.PLUGIN_NAME}} from master.
        files: ./plugin/${{env.PLUGIN_NAME}}
