name: Rust Build

env:
  PLUGIN_NAME: 'libparam_hook.nro'
  VERSION: 'v13.0.2'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  plugin:
    name: Plugin NRO
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          target: x86_64-unknown-linux-gnu
      - name: Install Skyline
        run: |
          cargo install cargo-skyline
          cargo-skyline skyline update-std
      - name: Build release NRO
        id: build_release
        run: RUSTFLAGS=-g cargo-skyline skyline build --release
      - name: Upload plugin artifact
        uses: actions/upload-artifact@v3
        with:
          name: plugin
          path: target/aarch64-skyline-switch/release/${{env.PLUGIN_NAME}}
